// include file for all parts
#include "Starfield.h"
#include "Planet.h"
#include "Voxel.h"
#include "Vectorizer.h"
#include "VectorizerWire.h"
#include "Morph.h"
#include "Rotzoom.h"
#include "City.h"
#include "MotionBlur.h"
#include "Greets.h"
#include "Frac.h"
#include "Logo.h"
#include "StarWars.h"
#include "Empty.h"
